### PR TITLE
allow configurable dict key for cluster label

### PR DESCRIPTION
**Pull request by 3wille**
adds function arguments that are used to access/set the dict key to save
the cluster label

### CODE REVIEW

**Comment by 3wille** [comment]
Hi, I need to configure the key for cluster labels and thought this might be interesting to the project as well. I looked for a way to configure this as a variable but my search didn't bring up any quick way.

**Comment by dustalov** [comment]
Hi, I think this would be useful. I will be happy to merge this PR after two adjustments:

1. Please add the unit test for this functionality to `test_chinese_whispers.py`.
2. Kindly make sure all the tests are passing by updating the type annotations in the source code.

**Comment by 3wille** [comment]
For the tests I tried to stay close to the previous tests without changing them. If you had something different in mind, please let me know

**Comment by dustalov** [comment]
Thank you!

**Pull request merged**
